/home/idveiwd-07/miniforge3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([32, 1])) that is different to the input size (torch.Size([32, 32])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/idveiwd-07/miniforge3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([2, 1])) that is different to the input size (torch.Size([2, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "/home/idveiwd-07/AA276/MPC_based_Reachability/main_train.py", line 151, in <module>
    V_prev = compute_recursive_value(x,
TypeError: compute_recursive_value() takes 4 positional arguments but 5 were given
