/home/idveiwd-07/miniforge3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([64, 1])) that is different to the input size (torch.Size([64, 64])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "/home/idveiwd-07/AA276/MPC_based_Reachability/main_train.py", line 135, in <module>
    T_f = T_f.expand(x.shape[0],1)
RuntimeError: The expanded size of the tensor (16) must match the existing size (64) at non-singleton dimension 0.  Target sizes: [16, 1].  Tensor sizes: [64, 1]
